- hosts: webservers
  tasks:
    - name: Install Docker
      become: yes
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: chariot97/petclinic
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: spring-petclinic
        image: chariot97/petclinic:latest
        state: started
        ports:
          - "8080:8080"
