- hosts: webservers
  become: yes
  tasks:
    - name: Ensure Python 3 is installed
      package:
        name: python3
        state: present

    - name: Install Docker on Debian-based systems
      when: ansible_os_family == "Debian"
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker on RedHat-based systems
      when: ansible_os_family == "RedHat"
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: chariot97/petclinic
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: spring-petclinic
        image: chariot97/petclinic:latest
        state: started
        ports:
          - "8080:8080"
